### ISSUE TITLE
Ryu shortest path with Mininet-wifi

### ISSUE THREAD

**Issue by as74150** [wagerpascal/665final#1]
Hello，I want to ask the question about Ryu shortest path with Mininet-wifi which in https://github.com/intrig-unicamp/mininet-wifi/issues/65. I need some suggestion and help！
I’m sorry that I can't find your email so ask the question here.

**Comment by wagerpascal** [comment]
Hey there,

So it's been a year since I did that project as it was for a class, but it seems I don't have the code anymore. I'm not sure how much Mininet-wifi has changed since then, but I do vaguely remember my setup- I'm pretty sure I took the Mininet-Wifi vm and then ran Ryu with it. I'm pretty sure after that it was pretty similar to that of regular Mininet after that outside of a few dependencies. Sorry I couldn't be of more help.

**Comment by as74150** [comment]
Dear wagerpascal：
Thanks for your reply, and I will try to solve the problem.
